# Generated by Django 3.0.6 on 2020-07-30 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=25)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stores', serialize=False, to='app.User')),
                ('is_open', models.BooleanField(blank=True, null=True)),
                ('opening_days', models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wendnesday'), ('Th', 'Monday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('completion_time', models.TimeField(blank=True, null=True)),
                ('fullfilled_successfully', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('user_did_not_present', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='app.User')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='app.Store')),
            ],
        ),
    ]
