# Generated by Django 3.0.6 on 2020-08-09 14:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200804_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abandonded_queues',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=20),
        ),
    ]
