# Generated by Django 3.0.6 on 2020-08-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200809_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='abandonded_queues',
            new_name='abandoned_queues',
        ),
    ]
