# Generated by Django 2.1.15 on 2020-07-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200704_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='fullfilled',
            field=models.BooleanField(default=False),
        ),
    ]
