# Generated by Django 3.0.6 on 2020-08-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_active_queues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_queues',
            new_name='infractions',
        ),
    ]
