# Generated by Django 3.0.6 on 2020-08-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200809_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='abandoned_queues',
            new_name='active_queues',
        ),
    ]
