# Generated by Django 2.1.15 on 2020-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_store_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_open',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
