# Generated by Django 2.1.15 on 2020-07-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200713_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='fullfilled',
            new_name='fullfilled_successfully',
        ),
        migrations.AddField(
            model_name='turn',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turn',
            name='user_did_not_present',
            field=models.BooleanField(default=False),
        ),
    ]
