# Generated by Django 3.0.6 on 2020-07-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200720_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='opening_days',
            field=models.CharField(blank=True, choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wendnesday'), ('Th', 'Monday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2, null=True),
        ),
    ]
