# Generated by Django 3.0.6 on 2020-07-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_store_opening_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_days',
            field=models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wendnesday'), ('Th', 'Monday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
